name: Sync to BookViewerApp3 repo

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Checkout Target
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: target
          repository: kurema/BookViewerApp3
          token: ${{ secrets.PAT_GitHub }}

      - name: Copy
        run: |
          #rm -rf target/*
          cp -rf main/Pages/* target
          
      - name: Push
        working-directory: ./target
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "sync"
          git push
